require('dotenv').config(); // Load environment variables
const express = require('express');
const axios = require('axios');
const cors = require('cors');

const app = express();

// Middleware
app.use(cors());
app.use(express.json());

// Gemini API configuration
const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent';
const GEMINI_API_KEY = 'AIzaSyCUzpgJqzBXjLOmqO9l340YlyH5AqLyJWk';

async function getResponse(text) {
    try {
        console.log('Prompt sent to Gemini API:', text);

        // Call Gemini API
        const response = await axios.post(
            `${GEMINI_API_URL}?key=${GEMINI_API_KEY}`,
            {
                contents: [{ parts: [{ text }] }],
            },
            {
                headers: {
                    'Content-Type': 'application/json',
                },
            }
        );

        console.log('Gemini API Response:', response.data);

        const reply = response.data.candidates[0].content.parts[0].text;
        return reply
    } catch (error) {
        console.error('Error calling Gemini API:', error.response ? error.response.data : error.message);
        return false
    }
}

// Route to generate itinerary or handle general questions
app.post('/generate-itinerary', async (req, res) => {
    const { from, to, startDate, endDate, numberOfPeople, groupType, additionalInfo, interests, followUpQuestion, itinerary } = req.body;

    console.log('Request Body:', req.body);

    let prompt = '';
    if (!followUpQuestion) {
        prompt = `
        You are a travel agent. Based on the following data, please generate a travel itinerary in Markdown format with clear headings, subheadings, and proper text formatting. **DO NOT assume any information beyond what is provided.**

**Provided Data Fields:**
- **StartDate:** ${startDate}
- **EndDate:** ${endDate}
- **From:** ${from}
- **To:** ${to}
- **NumberofPeople:** ${numberOfPeople}
- **GroupType:** ${groupType}
- **Interests:** ${interests}
- **AdditionalInfo:** ${additionalInfo}

**Instructions:**
1. **Itinerary Overview:**  
   - Include the trip dates, starting point, destination, group details, interests, and any additional information.
2. **Itinerary Details:**  
   - For each segment or day of the trip, provide the following:
     - **Location Name:** Clearly state the name of the location or transit point.
     - **Location Description:** Write a description of the location based solely on the provided data.
     - **Estimated Time:** Specify the estimated time to visit or transit through this location.
     - **Best Travel Method:** Describe the best possible way to travel to or from this location based on the data.
3. **Formatting:**  
   - Use Markdown syntax for headings to organize the itinerary.
   - Use bold text for key details like dates, locations, and travel methods.
   - Use bullet points or numbered lists as needed for clarity.

**Example Output Format:**

# Travel Itinerary

## Trip Overview
- **Start Date:** [StartDate]
- **End Date:** [EndDate]
- **Departure:** [From]
- **Destination:** [To]
- **Number of People:** [NumberofPeople]
- **Group Type:** [GroupType]
- **Interests:** [Interests]
- **Additional Info:** [AdditionalInfo]

---

## Day 1: [Location Name]
**Description:**  
[Provide a description of the location based on the provided data.]

**Estimated Time:**  
[Estimated time at the location or transit duration.]

**Travel Method:**  
[Describe the best possible way of travel based on the data.]

---

*Repeat the above section for subsequent days or travel segments as applicable.*

Please generate the complete itinerary using only the above provided data.

        `
    }
    else {
        prompt = `
        You are a travel assistant. Below is a travel itinerary in Markdown format that was generated by you. Your task is to answer the follow-up question using. If the itinerary does not contain sufficient details to fully answer the question, please state that clearly.

        Use the provided itinerary to answer the follow-up question. **DO NOT assume any information beyond what is provided.**
        ## Trip Overview
- **Start Date:** [StartDate]
- **End Date:** [EndDate]
- **Departure:** [From]
- **Destination:** [To]
- **Number of People:** [NumberofPeople]
- **Group Type:** [GroupType]
- **Interests:** [Interests]
- **Additional Info:** [AdditionalInfo]

**Instructions:**
1. **Review the Itinerary:**  
   Carefully read the itinerary provided below. Take note of all the dates, locations, travel methods, and any additional details included.

2. **Answer the Follow-Up Question:**  
   Based solely on the details in the itinerary, provide a complete answer to the follow-up question. Format your answer in Markdown with clear headings and bullet points if needed.

3. **Add extra details if the user asks for them:**
    If the user asks for more information, you can provide additional details based on the context of the itinerary. You can add places to visit, activities to do, or any other relevant information. But do not modify the Start Date, End Date, From, To, Number of People, Group Type, Interests, Additional Info, or the Itinerary.

4. **Itenerary:**
        The itenerary is generated by you only so do not tell the user the itenerary is wrong or right or does not contain enough information. You can even add more information to the itenerary if you want.
        
---

### Travel Itinerary:
${itinerary}

---

### Follow-Up Question:
${followUpQuestion}

---

Please provide your answer in Markdown format.

        `
    }

    try {
        const response = await getResponse(prompt);
        console.log(response);
        res.json({ data: response });
    }
    catch (error) {
        console.error('Error:', error);
        res.status(500).json({ error: 'Failed to generate response.' });
    }
});

// Start the server
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
    console.log(`Server is running on http://localhost:${PORT}`);
});
